# Generated by Django 4.2 on 2023-05-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_store_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='product_image',
            new_name='product_images',
        ),
    ]
