# Generated by Django 4.2 on 2023-05-20 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_product_image_store_product_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='store',
            name='product_images',
            field=models.ImageField(blank=True, null=True, upload_to='photos/product_images'),
        ),
    ]
